//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/FaceMesage.proto
namespace proto.FaceMesage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FaceMesage")]
  public partial class FaceMesage : global::ProtoBuf.IExtensible
  {
    public FaceMesage() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private long _timestamp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private string _mallId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"mallId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mallId
    {
      get { return _mallId; }
      set { _mallId = value; }
    }
    private string _terminalId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"terminalId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string terminalId
    {
      get { return _terminalId; }
      set { _terminalId = value; }
    }
    private string _terminalMac;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"terminalMac", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string terminalMac
    {
      get { return _terminalMac; }
      set { _terminalMac = value; }
    }

    private Face _face = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"face", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Face face
    {
      get { return _face; }
      set { _face = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Face")]
  public partial class Face : global::ProtoBuf.IExtensible
  {
    public Face() {}
    

    private long _enterTime = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"enterTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long enterTime
    {
      get { return _enterTime; }
      set { _enterTime = value; }
    }

    private long _leaveTime = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"leaveTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long leaveTime
    {
      get { return _leaveTime; }
      set { _leaveTime = value; }
    }

    private string _position = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string position
    {
      get { return _position; }
      set { _position = value; }
    }

    private byte[] _faceImage = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"faceImage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] faceImage
    {
      get { return _faceImage; }
      set { _faceImage = value; }
    }

    private string _imageMimeType = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"imageMimeType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string imageMimeType
    {
      get { return _imageMimeType; }
      set { _imageMimeType = value; }
    }
    private global::System.Collections.Generic.List<float> _landMarks = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(6, Name=@"landMarks", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<float> landMarks
    {
      get { return _landMarks; }
            set { _landMarks = value; }
        }
  

    private string _eventType = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"eventType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string eventType
    {
      get { return _eventType; }
      set { _eventType = value; }
    }

    private double _imageWidth = default(double);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"imageWidth", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double imageWidth
    {
      get { return _imageWidth; }
      set { _imageWidth = value; }
    }

    private double _imageHeight = default(double);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"imageHeight", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double imageHeight
    {
      get { return _imageHeight; }
      set { _imageHeight = value; }
    }

    private Profile _profile = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"profile", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Profile profile
    {
      get { return _profile; }
      set { _profile = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Profile")]
  public partial class Profile : global::ProtoBuf.IExtensible
  {
    public Profile() {}
    

    private string _beginAge = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"beginAge", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string beginAge
    {
      get { return _beginAge; }
      set { _beginAge = value; }
    }

    private string _endAge = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"endAge", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string endAge
    {
      get { return _endAge; }
      set { _endAge = value; }
    }

    private string _gender = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"gender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gender
    {
      get { return _gender; }
      set { _gender = value; }
    }

    private int _faceCode = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"faceCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int faceCode
    {
      get { return _faceCode; }
      set { _faceCode = value; }
    }

    private string _expression = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"expression", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string expression
    {
      get { return _expression; }
      set { _expression = value; }
    }

    private bool _wearGlasses = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"wearGlasses", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool wearGlasses
    {
      get { return _wearGlasses; }
      set { _wearGlasses = value; }
    }

    private double _ageConfidence = default(double);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"ageConfidence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double ageConfidence
    {
      get { return _ageConfidence; }
      set { _ageConfidence = value; }
    }

    private double _genderConfidence = default(double);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"genderConfidence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double genderConfidence
    {
      get { return _genderConfidence; }
      set { _genderConfidence = value; }
    }

    private double _expressionConfidence = default(double);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"expressionConfidence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double expressionConfidence
    {
      get { return _expressionConfidence; }
      set { _expressionConfidence = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}