//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/human_face_report.proto
namespace rongyi.face.log
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserProfile")]
  public partial class UserProfile : global::ProtoBuf.IExtensible
  {
    public UserProfile() {}
    

    private int _begin_age = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"begin_age", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int begin_age
    {
      get { return _begin_age; }
      set { _begin_age = value; }
    }

    private int _end_age = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"end_age", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int end_age
    {
      get { return _end_age; }
      set { _end_age = value; }
    }

    private rongyi.face.log.Gender _gender = rongyi.face.log.Gender.GENDER_UNKNOWN;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"gender", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(rongyi.face.log.Gender.GENDER_UNKNOWN)]
    public rongyi.face.log.Gender gender
    {
      get { return _gender; }
      set { _gender = value; }
    }

    private byte[] _face_code = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"face_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] face_code
    {
      get { return _face_code; }
      set { _face_code = value; }
    }

    private rongyi.face.log.UserExpression _expression = rongyi.face.log.UserExpression.UserExpressionUnknown;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"expression", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(rongyi.face.log.UserExpression.UserExpressionUnknown)]
    public rongyi.face.log.UserExpression expression
    {
      get { return _expression; }
      set { _expression = value; }
    }

    private bool _wear_glasses = (bool)false;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"wear_glasses", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool wear_glasses
    {
      get { return _wear_glasses; }
      set { _wear_glasses = value; }
    }

    private double _age_confidence = default(double);
    [global::ProtoBuf.ProtoMember(1001, IsRequired = false, Name=@"age_confidence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double age_confidence
    {
      get { return _age_confidence; }
      set { _age_confidence = value; }
    }

    private double _gender_confidence = default(double);
    [global::ProtoBuf.ProtoMember(1002, IsRequired = false, Name=@"gender_confidence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double gender_confidence
    {
      get { return _gender_confidence; }
      set { _gender_confidence = value; }
    }

    private double _expression_confidence = default(double);
    [global::ProtoBuf.ProtoMember(1003, IsRequired = false, Name=@"expression_confidence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double expression_confidence
    {
      get { return _expression_confidence; }
      set { _expression_confidence = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CapturedUserFace")]
  public partial class CapturedUserFace : global::ProtoBuf.IExtensible
  {
    public CapturedUserFace() {}
    

    private rongyi.face.log.UserProfile _profile = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"profile", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public rongyi.face.log.UserProfile profile
    {
      get { return _profile; }
      set { _profile = value; }
    }

    private long _enter_time = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"enter_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long enter_time
    {
      get { return _enter_time; }
      set { _enter_time = value; }
    }

    private long _leave_time = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"leave_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long leave_time
    {
      get { return _leave_time; }
      set { _leave_time = value; }
    }

    private rongyi.face.log.FacePosition _position = rongyi.face.log.FacePosition.FacePositionPositive;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(rongyi.face.log.FacePosition.FacePositionPositive)]
    public rongyi.face.log.FacePosition position
    {
      get { return _position; }
      set { _position = value; }
    }

    private byte[] _face_image = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"face_image", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] face_image
    {
      get { return _face_image; }
      set { _face_image = value; }
    }

    private byte[] _image_mime_type = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"image_mime_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] image_mime_type
    {
      get { return _image_mime_type; }
      set { _image_mime_type = value; }
    }
    private global::System.Collections.Generic.List<int> _land_marks = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(7, Name=@"land_marks", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> land_marks
    {
      get { return _land_marks; }
            set { _land_marks = value; }
        }
  

    private rongyi.face.log.FaceEventType _event_type = rongyi.face.log.FaceEventType.NO_EVENT;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"event_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(rongyi.face.log.FaceEventType.NO_EVENT)]
    public rongyi.face.log.FaceEventType event_type
    {
      get { return _event_type; }
      set { _event_type = value; }
    }

    private int _image_width = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"image_width", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int image_width
    {
      get { return _image_width; }
      set { _image_width = value; }
    }

    private int _image_height = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"image_height", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int image_height
    {
      get { return _image_height; }
      set { _image_height = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReportID")]
  public partial class ReportID : global::ProtoBuf.IExtensible
  {
    public ReportID() {}
    

    private byte[] _terminal_id = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"terminal_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] terminal_id
    {
      get { return _terminal_id; }
      set { _terminal_id = value; }
    }

    private long _timestamp = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }

    private long _index = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long index
    {
      get { return _index; }
      set { _index = value; }
    }

    private byte[] _terminal_mac = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"terminal_mac", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] terminal_mac
    {
      get { return _terminal_mac; }
      set { _terminal_mac = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserFaceInfo")]
  public partial class UserFaceInfo : global::ProtoBuf.IExtensible
  {
    public UserFaceInfo() {}
    
    private byte[] _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] id
    {
      get { return _id; }
      set { _id = value; }
    }

    private long _timestamp = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }

    private byte[] _mall_id = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"mall_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] mall_id
    {
      get { return _mall_id; }
      set { _mall_id = value; }
    }

    private byte[] _terminal_id = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"terminal_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] terminal_id
    {
      get { return _terminal_id; }
      set { _terminal_id = value; }
    }
    private global::System.Collections.Generic.List<rongyi.face.log.CapturedUserFace> _face = new global::System.Collections.Generic.List<rongyi.face.log.CapturedUserFace>();
    [global::ProtoBuf.ProtoMember(5, Name=@"face", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<rongyi.face.log.CapturedUserFace> face
    {
      get { return _face; }
       set { _face = value; }
        }
  

    private byte[] _terminal_mac = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"terminal_mac", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] terminal_mac
    {
      get { return _terminal_mac; }
      set { _terminal_mac = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"UserExpression")]
    public enum UserExpression
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UserExpressionUnknown", Value=0)]
      UserExpressionUnknown = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Happy", Value=1)]
      Happy = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Afraifd", Value=2)]
      Afraifd = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Surprised", Value=3)]
      Surprised = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Sad", Value=4)]
      Sad = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Angry", Value=5)]
      Angry = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Serene", Value=6)]
      Serene = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Depressed", Value=7)]
      Depressed = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UserExpressionOthers", Value=1000)]
      UserExpressionOthers = 1000
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"FacePosition")]
    public enum FacePosition
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FacePositionPositive", Value=0)]
      FacePositionPositive = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FacePositionSide", Value=1)]
      FacePositionSide = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FacePositionOthers", Value=1000)]
      FacePositionOthers = 1000
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Gender")]
    public enum Gender
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GENDER_UNKNOWN", Value=0)]
      GENDER_UNKNOWN = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GENDER_MALE", Value=1)]
      GENDER_MALE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GENDER_FEMALE", Value=2)]
      GENDER_FEMALE = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"LandMarkType")]
    public enum LandMarkType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LEFT_EYE_CENTER", Value=1)]
      LEFT_EYE_CENTER = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RIGHT_EYE_CENTER", Value=2)]
      RIGHT_EYE_CENTER = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOSE_TIP", Value=3)]
      NOSE_TIP = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LEFT_MOUSE_CORNER", Value=4)]
      LEFT_MOUSE_CORNER = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RIGHT_MOUSE_CORNER", Value=5)]
      RIGHT_MOUSE_CORNER = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"FaceEventType")]
    public enum FaceEventType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_EVENT", Value=0)]
      NO_EVENT = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENTER_SIGHT", Value=1)]
      ENTER_SIGHT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DETECT_INFO", Value=2)]
      DETECT_INFO = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COME_CLOSE", Value=3)]
      COME_CLOSE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LEAVE_SIGHT", Value=-1)]
      LEAVE_SIGHT = -1
    }
  
}